name: flyer
description: "A powerful CLI package to speed up Flutter app development by automating repetitive tasks like creating features, pages, forms, and generating Dart model classes from JSON and reformatting code and more. Additionally, it initializes your Flutter project's infrastructure and installs essential packages."
version: 0.0.4
homepage: https://github.com/abdo-ahmed-it/flyer

environment:
  sdk: ">=3.5.0 <4.0.0"

executables:
  flyer: bin/flyer.dart

dependencies:
  yaml: ^3.1.0
  flutter:
    sdk: flutter
  dart_style: ^2.3.7
  json_ast: ^1.0.6
  args: ^2.6.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0