/// String templates for iOS CI/CD files generated by `flyer ci:ios`.
///
/// Templates use simple `{{KEY}}` placeholders substituted by [render].
class CiTemplates {
  static String render(String template, Map<String, String> vars) {
    var out = template;
    vars.forEach((key, value) {
      out = out.replaceAll('{{$key}}', value);
    });
    return out;
  }

  /// GitHub Actions workflow. Shorebird lane options are always present so the
  /// workflow keeps working whether or not Shorebird was set up — the setup
  /// step is gated on the `lane` input.
  static const workflow = r'''name: Deploy iOS to TestFlight

on:
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane to run"
        required: true
        default: "{{DEFAULT_LANE}}"
        type: choice
        options:
          - release_shorebird
          - patch_shorebird
          - deploy

env:
  FLUTTER_VERSION: "{{FLUTTER_VERSION}}"
  RUBY_VERSION: "3.2"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  deploy_ios:
    name: Deploy iOS to TestFlight (${{ inputs.lane }})
    runs-on: macos-26
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.1.1"

      - name: Ensure iOS simulator runtime is installed
        run: |
          xcodebuild -version
          sudo xcodebuild -downloadPlatform iOS

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Set up Shorebird
        if: inputs.lane == 'release_shorebird' || inputs.lane == 'patch_shorebird'
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: ios

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Cache Flutter pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Precache iOS artifacts
        run: flutter precache --ios

      - name: Install CocoaPods
        working-directory: ios
        run: bundle exec pod install

      - name: Deploy to TestFlight via Fastlane
        working-directory: ios
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        run: bundle exec fastlane ${{ inputs.lane }}

      - name: Upload IPA artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
          if-no-files-found: warn
          retention-days: 14

      - name: Upload Fastlane logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fastlane-logs
          path: |
            ios/fastlane/report.xml
            ~/Library/Logs/gym/**
          if-no-files-found: ignore
          retention-days: 7

      - name: Notify Lark
        if: always() && env.LARK_WEBHOOK != ''
        env:
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
          JOB_STATUS: ${{ job.status }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          ACTOR: ${{ github.actor }}
          LANE: ${{ inputs.lane }}
        run: |
          if [ "$JOB_STATUS" = "success" ]; then
            TEMPLATE="green"
            TITLE="✅ iOS Deploy to TestFlight — SUCCESS"
          elif [ "$JOB_STATUS" = "failure" ]; then
            TEMPLATE="red"
            TITLE="❌ iOS Deploy to TestFlight — FAILED"
          else
            TEMPLATE="grey"
            TITLE="⚠️ iOS Deploy to TestFlight — ${JOB_STATUS}"
          fi

          SHORT_SHA="${COMMIT_SHA:0:7}"
          FIRST_LINE_MSG=$(printf '%s' "$COMMIT_MSG" | head -n 1)

          PAYLOAD=$(jq -n \
            --arg template "$TEMPLATE" \
            --arg title "$TITLE" \
            --arg repo "$REPO" \
            --arg branch "$BRANCH" \
            --arg lane "$LANE" \
            --arg actor "$ACTOR" \
            --arg short_sha "$SHORT_SHA" \
            --arg commit_msg "$FIRST_LINE_MSG" \
            --arg commit_url "$COMMIT_URL" \
            --arg run_url "$RUN_URL" \
            '{
              msg_type: "interactive",
              card: {
                config: { wide_screen_mode: true },
                header: {
                  template: $template,
                  title: { tag: "plain_text", content: $title }
                },
                elements: [
                  {
                    tag: "div",
                    fields: [
                      { is_short: true, text: { tag: "lark_md", content: ("**Repository:**\n" + $repo) } },
                      { is_short: true, text: { tag: "lark_md", content: ("**Branch:**\n" + $branch) } },
                      { is_short: true, text: { tag: "lark_md", content: ("**Lane:**\n" + $lane) } },
                      { is_short: true, text: { tag: "lark_md", content: ("**Actor:**\n" + $actor) } }
                    ]
                  },
                  {
                    tag: "div",
                    text: { tag: "lark_md", content: ("**Commit:** [`" + $short_sha + "`](" + $commit_url + ") " + $commit_msg) }
                  },
                  { tag: "hr" },
                  {
                    tag: "action",
                    actions: [
                      {
                        tag: "button",
                        text: { tag: "plain_text", content: "View Workflow Run" },
                        type: "primary",
                        url: $run_url
                      }
                    ]
                  }
                ]
              }
            }')

          curl -s -X POST "$LARK_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
''';

  static const fastfile = r'''default_platform(:ios)

APP_IDENTIFIER = "{{BUNDLE_ID}}"
TEAM_ID = "{{TEAM_ID}}"
PROFILE_NAME = "match AppStore #{APP_IDENTIFIER}"

platform :ios do
  # Installs the App Store Connect API key, syncs match certificates, bumps the
  # build number, and forces manual signing on Runner/RunnerTests. Returns the
  # api_key so callers can reuse it for uploads.
  def prepare_signing
    setup_ci(provider: "travis")

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false
    )

    match(
      type: "appstore",
      app_identifier: APP_IDENTIFIER,
      readonly: true,
      api_key: api_key
    )

    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      build_number: latest_testflight_build_number(
        app_identifier: APP_IDENTIFIER,
        api_key: api_key
      ) + 1
    )

    %w[Debug Release Profile].each do |config|
      update_code_signing_settings(
        use_automatic_signing: false,
        path: "Runner.xcodeproj",
        targets: ["Runner"],
        build_configurations: [config],
        team_id: TEAM_ID,
        bundle_identifier: APP_IDENTIFIER,
        profile_name: PROFILE_NAME,
        code_sign_identity: "Apple Distribution"
      )

      update_code_signing_settings(
        use_automatic_signing: false,
        path: "Runner.xcodeproj",
        targets: ["RunnerTests"],
        build_configurations: [config],
        team_id: TEAM_ID,
        bundle_identifier: "#{APP_IDENTIFIER}.RunnerTests",
        code_sign_identity: ""
      )
    end

    api_key
  end

  desc "Push a new native-only beta build to TestFlight (no Shorebird)"
  lane :deploy do
    api_key = prepare_signing

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      configuration: "Release",
      output_directory: "../build/ios/ipa",
      clean: true,
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        method: "app-store",
        signingStyle: "manual",
        teamID: TEAM_ID,
        provisioningProfiles: {
          APP_IDENTIFIER => PROFILE_NAME
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      app_identifier: APP_IDENTIFIER
    )
  end

  desc "Push a new Shorebird release to TestFlight (enables future code pushes)"
  lane :release_shorebird do
    api_key = prepare_signing

    shorebird_release(
      platform: "ios",
      args: "-- --export-options-plist=#{File.expand_path('../ExportOptions.plist', __dir__)}"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      app_identifier: APP_IDENTIFIER,
      ipa: lane_context[SharedValues::IPA_OUTPUT_PATH]
    )
  end

  desc "Ship a Shorebird code push patch to existing users (no App Store review)"
  lane :patch_shorebird do
    shorebird_patch(
      platform: "ios"
    )
  end
end
''';

  static const appfile = r'''app_identifier("{{BUNDLE_ID}}")
''';

  static const matchfile = r'''git_url(ENV["MATCH_GIT_URL"] || "{{MATCH_GIT_URL}}")
storage_mode("git")
type("appstore")
app_identifier(["{{BUNDLE_ID}}"])

api_key_path("fastlane/api_key.json") if File.exist?(File.expand_path("api_key.json", __dir__))
''';

  static const pluginfile = r'''# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-shorebird'
''';

  static const gemfile = r'''source "https://rubygems.org"

gem "fastlane"
gem "cocoapods"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
''';

  static const exportOptions = r'''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>
    <string>app-store</string>
    <key>signingStyle</key>
    <string>manual</string>
    <key>teamID</key>
    <string>{{TEAM_ID}}</string>
    <key>provisioningProfiles</key>
    <dict>
        <key>{{BUNDLE_ID}}</key>
        <string>match AppStore {{BUNDLE_ID}}</string>
    </dict>
    <key>stripSwiftSymbols</key>
    <true/>
    <key>uploadSymbols</key>
    <true/>
</dict>
</plist>
''';

  /// Podfile post_install block — applied as an edit, not a full file replace.
  static const podfilePostInstall = r'''post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end

  installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete('CODE_SIGNING_ALLOWED')
    config.build_settings.delete('CODE_SIGNING_REQUIRED')
  end
end''';

  /// .gitignore entries that should be added for iOS CI.
  static const gitignoreEntries = [
    'ios/fastlane/api_key.json',
    'ios/fastlane/report.xml',
    'ios/fastlane/Preview.html',
    'ios/fastlane/screenshots',
    'ios/fastlane/test_output',
    'ios/vendor/',
  ];
}
